"""Add BOLA, Idempotency, and Audit Hash

Revision ID: 05f0b4de641c
Revises: 2c5d8d476266
Create Date: 2026-07-04 19:07:42.587074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05f0b4de641c'
down_revision: Union[str, Sequence[str], None] = '2c5d8d476266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('request_hash', sa.String(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotency_records_idempotency_key'), 'idempotency_records', ['idempotency_key'], unique=True)
    op.add_column('audit_events', sa.Column('case_version', sa.Integer(), nullable=True))
    op.add_column('audit_events', sa.Column('prior_event_hash', sa.String(), nullable=True))
    op.add_column('audit_events', sa.Column('event_hash', sa.String(), nullable=True))
    op.add_column('audit_events', sa.Column('reason', sa.String(), nullable=True))
    op.drop_index(op.f('ix_audit_events_correlation_id'), table_name='audit_events')
    op.drop_column('audit_events', 'correlation_id')
    op.add_column('cases', sa.Column('assigned_relationship_manager_id', sa.UUID(), nullable=True))
    op.add_column('cases', sa.Column('assigned_credit_analyst_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'cases', 'users', ['assigned_credit_analyst_id'], ['id'])
    op.create_foreign_key(None, 'cases', 'users', ['assigned_relationship_manager_id'], ['id'])
    op.add_column('sessions', sa.Column('csrf_token_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'csrf_token_hash')
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_column('cases', 'assigned_credit_analyst_id')
    op.drop_column('cases', 'assigned_relationship_manager_id')
    op.add_column('audit_events', sa.Column('correlation_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_audit_events_correlation_id'), 'audit_events', ['correlation_id'], unique=False)
    op.drop_column('audit_events', 'reason')
    op.drop_column('audit_events', 'event_hash')
    op.drop_column('audit_events', 'prior_event_hash')
    op.drop_column('audit_events', 'case_version')
    op.drop_index(op.f('ix_idempotency_records_idempotency_key'), table_name='idempotency_records')
    op.drop_table('idempotency_records')
    # ### end Alembic commands ###
