"""Add case decision fields

Revision ID: 2c5d8d476266
Revises: e5852182338a
Create Date: 2026-07-04 16:21:39.048036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c5d8d476266'
down_revision: Union[str, Sequence[str], None] = 'e5852182338a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from sqlalchemy.dialects import postgresql
    
    analyst_enum = postgresql.ENUM('RECOMMEND_ALTERNATIVE_STRUCTURE', 'REQUEST_ADDITIONAL_EVIDENCE', 'RECOMMEND_ENHANCED_DUE_DILIGENCE', name='analystrecommendationaction')
    analyst_enum.create(op.get_bind())
    
    human_enum = postgresql.ENUM('APPROVE_AS_REQUESTED', 'APPROVE_ALTERNATIVE_STRUCTURE', 'DEFER_FOR_EVIDENCE', 'ESCALATE_FOR_DUE_DILIGENCE', 'DECLINE_AFTER_HUMAN_REVIEW', name='humandecisionaction')
    human_enum.create(op.get_bind())
    
    op.add_column('cases', sa.Column('analyst_recommendation', sa.Enum('RECOMMEND_ALTERNATIVE_STRUCTURE', 'REQUEST_ADDITIONAL_EVIDENCE', 'RECOMMEND_ENHANCED_DUE_DILIGENCE', name='analystrecommendationaction'), nullable=True))
    op.add_column('cases', sa.Column('human_decision', sa.Enum('APPROVE_AS_REQUESTED', 'APPROVE_ALTERNATIVE_STRUCTURE', 'DEFER_FOR_EVIDENCE', 'ESCALATE_FOR_DUE_DILIGENCE', 'DECLINE_AFTER_HUMAN_REVIEW', name='humandecisionaction'), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'human_decision')
    op.drop_column('cases', 'analyst_recommendation')
    # ### end Alembic commands ###
