"""Add AssessmentSnapshot

Revision ID: 36029ce44378
Revises: 3f9b4d2a8c77
Create Date: 2026-07-12 12:44:54.555864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36029ce44378'
down_revision: Union[str, Sequence[str], None] = '3f9b4d2a8c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('case_version', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feature_snapshot', sa.JSON(), nullable=False),
    sa.Column('canonical_assessment_json', sa.JSON(), nullable=False),
    sa.Column('engine_versions', sa.JSON(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'case_version', name='uq_assessment_case_version')
    )
    op.create_index(op.f('ix_assessment_snapshots_assessment_id'), 'assessment_snapshots', ['assessment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_snapshots_assessment_id'), table_name='assessment_snapshots')
    op.drop_table('assessment_snapshots')
    # ### end Alembic commands ###
