"""Phase 1.1.3 BOLA updates

Revision ID: 7c35182cf1b8
Revises: 05f0b4de641c
Create Date: 2026-07-05 11:14:47.030011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c35182cf1b8'
down_revision: Union[str, Sequence[str], None] = '05f0b4de641c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects.postgresql import ENUM

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Create ProductType Enum
    product_type_enum = ENUM('WORKING_CAPITAL_LINE', 'RECEIVABLES_FINANCE', 'TERM_LOAN', name='producttype', create_type=False)
    op.execute("CREATE TYPE producttype AS ENUM ('WORKING_CAPITAL_LINE', 'RECEIVABLES_FINANCE', 'TERM_LOAN')")

    # 2. Create tables
    op.create_table('regions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_code'), 'regions', ['code'], unique=True)
    op.create_table('branches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name='fk_branches_region_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_code'), 'branches', ['code'], unique=True)
    op.create_table('sanctioning_mandates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('region_id', sa.UUID(), nullable=True),
    sa.Column('product_type', product_type_enum, nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('maximum_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False, default=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('mandate_version', sa.Integer(), nullable=False, default=1),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_sanctioning_mandates_user_id'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='fk_sanctioning_mandates_branch_id'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name='fk_sanctioning_mandates_region_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_branch_scopes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('scope_role', sa.String(), nullable=False, default='PRIMARY'),
    sa.Column('can_read', sa.Boolean(), nullable=False, default=True),
    sa.Column('can_recommend', sa.Boolean(), nullable=False, default=False),
    sa.Column('active', sa.Boolean(), nullable=False, default=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='fk_user_branch_scopes_branch_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_branch_scopes_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # 3. Add new columns as NULLABLE first
    op.add_column('cases', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('cases', sa.Column('originating_branch_id', sa.UUID(), nullable=True))
    op.add_column('cases', sa.Column('assigned_sanctioning_authority_id', sa.UUID(), nullable=True))
    op.add_column('cases', sa.Column('requested_product', product_type_enum, nullable=True))
    
    op.create_foreign_key('fk_cases_originating_branch_id', 'cases', 'branches', ['originating_branch_id'], ['id'])
    op.create_foreign_key('fk_cases_assigned_sanctioning_authority_id', 'cases', 'users', ['assigned_sanctioning_authority_id'], ['id'])

    # 4. Backfill existing data
    op.execute("""
        UPDATE cases 
        SET currency = 'INR',
            requested_product = CASE 
                WHEN requested_facility_type = 'WORKING_CAPITAL' THEN 'WORKING_CAPITAL_LINE'::producttype
                WHEN requested_facility_type = 'TRADE_FINANCE' THEN 'RECEIVABLES_FINANCE'::producttype
                ELSE 'TERM_LOAN'::producttype
            END
    """)

    # 5. Make columns NOT NULL
    op.alter_column('cases', 'currency', existing_type=sa.String(), nullable=False)
    op.alter_column('cases', 'requested_product', existing_type=product_type_enum, nullable=False)

    # 6. Drop old column
    op.drop_column('cases', 'requested_facility_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('requested_facility_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    
    # Reverse backfill
    op.execute("""
        UPDATE cases 
        SET requested_facility_type = CASE 
            WHEN requested_product = 'WORKING_CAPITAL_LINE' THEN 'WORKING_CAPITAL'
            WHEN requested_product = 'RECEIVABLES_FINANCE' THEN 'TRADE_FINANCE'
            ELSE 'TERM_LOAN'
        END
    """)
    op.alter_column('cases', 'requested_facility_type', existing_type=sa.VARCHAR(), nullable=False)

    op.drop_constraint('fk_cases_assigned_sanctioning_authority_id', 'cases', type_='foreignkey')
    op.drop_constraint('fk_cases_originating_branch_id', 'cases', type_='foreignkey')
    op.drop_column('cases', 'requested_product')
    op.drop_column('cases', 'assigned_sanctioning_authority_id')
    op.drop_column('cases', 'originating_branch_id')
    op.drop_column('cases', 'currency')
    
    op.drop_table('user_branch_scopes')
    op.drop_table('sanctioning_mandates')
    op.drop_index(op.f('ix_branches_code'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_regions_code'), table_name='regions')
    op.drop_table('regions')
    
    op.execute("DROP TYPE producttype")
    # ### end Alembic commands ###
