"""Baseline canonical migration

Revision ID: d244551be18e
Revises: 
Create Date: 2026-07-04 16:09:02.386432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd244551be18e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesss',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesss_business_id'), 'businesss', ['business_id'], unique=True)
    op.create_table('bank_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id_fk', sa.UUID(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_environment', sa.String(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=False),
    sa.Column('ingestion_run_id', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('evidence_as_of', sa.DateTime(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('data_quality_status', sa.String(), nullable=False),
    sa.Column('provenance_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['business_id_fk'], ['businesss.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id_fk', sa.UUID(), nullable=False),
    sa.Column('requested_facility_type', sa.String(), nullable=False),
    sa.Column('requested_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'EVIDENCE_GATHERING', 'ASSESSMENT_COMPLETED', 'DECISION_PENDING', 'HUMAN_APPROVED', 'HUMAN_DECLINED', 'HUMAN_DEFERRED', name='casestatus'), nullable=False),
    sa.Column('recommendation', sa.Enum('READY_FOR_REVIEW', 'CONDITIONAL_OFFER', 'ADDITIONAL_EVIDENCE_REQUIRED', 'ENHANCED_DUE_DILIGENCE', 'DECLINE_RECOMMENDED', name='systemrecommendation'), nullable=True),
    sa.Column('monthly_revenue_inr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('dscr', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('cash_buffer_days', sa.Integer(), nullable=True),
    sa.Column('financial_health_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('data_confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('resilience_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id_fk'], ['businesss.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id_fk', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'EXPIRED', 'REVOKED', name='consentstatus'), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id_fk'], ['businesss.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataconnections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id_fk', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_sync_at', sa.Date(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id_fk'], ['businesss.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employment_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id_fk', sa.UUID(), nullable=False),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=False),
    sa.Column('total_pf_remittance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_environment', sa.String(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=False),
    sa.Column('ingestion_run_id', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('evidence_as_of', sa.DateTime(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('data_quality_status', sa.String(), nullable=False),
    sa.Column('provenance_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['business_id_fk'], ['businesss.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gst_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id_fk', sa.UUID(), nullable=False),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('declared_revenue', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('tax_paid', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_environment', sa.String(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=False),
    sa.Column('ingestion_run_id', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('evidence_as_of', sa.DateTime(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('data_quality_status', sa.String(), nullable=False),
    sa.Column('provenance_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['business_id_fk'], ['businesss.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id_fk', sa.UUID(), nullable=False),
    sa.Column('counterparty_name', sa.String(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_environment', sa.String(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=False),
    sa.Column('ingestion_run_id', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('evidence_as_of', sa.DateTime(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('data_quality_status', sa.String(), nullable=False),
    sa.Column('provenance_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['business_id_fk'], ['businesss.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obligations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id_fk', sa.UUID(), nullable=False),
    sa.Column('facility_type', sa.String(), nullable=False),
    sa.Column('monthly_emi', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('outstanding_balance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_environment', sa.String(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=False),
    sa.Column('ingestion_run_id', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('evidence_as_of', sa.DateTime(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('data_quality_status', sa.String(), nullable=False),
    sa.Column('provenance_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['business_id_fk'], ['businesss.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('actor_role', sa.String(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_audit_events_correlation_id'), 'audit_events', ['correlation_id'], unique=False)
    op.create_table('invoice_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id_fk', sa.UUID(), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_environment', sa.String(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=False),
    sa.Column('ingestion_run_id', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('evidence_as_of', sa.DateTime(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('data_quality_status', sa.String(), nullable=False),
    sa.Column('provenance_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id_fk'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_payments')
    op.drop_index(op.f('ix_audit_events_correlation_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('obligations')
    op.drop_table('invoices')
    op.drop_table('gst_periods')
    op.drop_table('employment_periods')
    op.drop_table('dataconnections')
    op.drop_table('consents')
    op.drop_table('cases')
    op.drop_table('bank_transactions')
    op.drop_index(op.f('ix_businesss_business_id'), table_name='businesss')
    op.drop_table('businesss')
    # ### end Alembic commands ###
