"""Phase 1.1.3 BOLA updates

Revision ID: f4ac18e8da3f
Revises: 05f0b4de641c
Create Date: 2026-07-04 22:48:40.612073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4ac18e8da3f'
down_revision: Union[str, Sequence[str], None] = '05f0b4de641c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_code'), 'regions', ['code'], unique=True)
    op.create_table('branches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_code'), 'branches', ['code'], unique=True)
    op.create_table('sanctioning_mandates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product', sa.Enum('WORKING_CAPITAL', 'TERM_LOAN', 'OVERDRAFT', 'TRADE_FINANCE', name='producttype'), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('max_tenor_months', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_branch_scopes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cases', sa.Column('originating_branch_id', sa.UUID(), nullable=True))
    op.add_column('cases', sa.Column('assigned_sanctioning_authority_id', sa.UUID(), nullable=True))
    op.add_column('cases', sa.Column('requested_product', sa.Enum('WORKING_CAPITAL', 'TERM_LOAN', 'OVERDRAFT', 'TRADE_FINANCE', name='producttype'), nullable=True))
    op.create_foreign_key(None, 'cases', 'users', ['assigned_sanctioning_authority_id'], ['id'])
    op.create_foreign_key(None, 'cases', 'branches', ['originating_branch_id'], ['id'])
    
    # DATA MIGRATION
    import uuid
    from datetime import datetime, timezone
    now = datetime.now(timezone.utc)
    
    hq_id = uuid.uuid4()
    main_branch_id = uuid.uuid4()
    
    op.execute(f"""
        INSERT INTO regions (id, code, name, created_at, updated_at) 
        VALUES ('{hq_id}', 'HQ', 'Headquarters', '{now}', '{now}')
    """)
    op.execute(f"""
        INSERT INTO branches (id, code, name, region_id, created_at, updated_at) 
        VALUES ('{main_branch_id}', 'MAIN', 'Main Branch', '{hq_id}', '{now}', '{now}')
    """)
    
    # Backfill existing Users -> attach to MAIN branch
    op.execute(f"""
        INSERT INTO user_branch_scopes (id, user_id, branch_id, created_at, updated_at)
        SELECT gen_random_uuid(), id, '{main_branch_id}', '{now}', '{now}' FROM users
    """)
    
    # Backfill existing Cases
    op.execute(f"""
        UPDATE cases 
        SET originating_branch_id = '{main_branch_id}', 
            requested_product = 'WORKING_CAPITAL'
    """)
    
    # Alter Columns: Make Case FKs non-nullable
    op.alter_column('cases', 'originating_branch_id', existing_type=sa.UUID(), nullable=False)
    op.alter_column('cases', 'requested_product', existing_type=sa.Enum('WORKING_CAPITAL', 'TERM_LOAN', 'OVERDRAFT', 'TRADE_FINANCE', name='producttype'), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_column('cases', 'requested_product')
    op.drop_column('cases', 'assigned_sanctioning_authority_id')
    op.drop_column('cases', 'originating_branch_id')
    op.drop_table('user_branch_scopes')
    op.drop_table('sanctioning_mandates')
    op.drop_index(op.f('ix_branches_code'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_regions_code'), table_name='regions')
    op.drop_table('regions')
    # ### end Alembic commands ###
