"""
Canonical Version Registry (`VER-001`)
Single source of truth across policy, calculations, schemas, and API endpoints.
"""

API_SERVICE_NAME = "vyapar-pulse-api"
API_VERSION = "3.0.0-rc3"
POLICY_VERSION = "2.0-CANONICAL"
CALCULATION_VERSION = "2.0-CANONICAL"
SCORING_VERSION = "3.0-EVIDENCE-CONDITIONED-FHI"
SCHEMA_VERSION = "2.0-CANONICAL"
PASSPORT_ENGINE_VERSION = "1.0-EVD-RC3"
FEATURE_SCHEMA_VERSION = "1.0-REPLAY-FEATURES"
PACKAGE_SCHEMA_VERSION = "1.0-DECISION-PACKAGE"
AUDIT_HASH_VERSION = "1.0-CANONICAL-AUDIT"
